
export const countryCapitalsTG: Record<string, string> = {
  "Afghanistan": "Кобул",
  "Albania": "Тирана",
  "Algeria": "Алҷозоир",
  "Andorra": "Андорра-ла-Велла",
  "Angola": "Луанда",
  "Antigua and Barbuda": "Сент Ҷонс",
  "Argentina": "Буэнос-Айрес",
  "Armenia": "Ереван",
  "Australia": "Канберра",
  "Austria": "Вена",
  "Azerbaijan": "Боку",
  "Bahamas": "Нассау",
  "Bahrain": "Манама",
  "Bangladesh": "Дакка",
  "Barbados": "Бриджтаун",
  "Belarus": "Минск",
  "Belgium": "Брюссел",
  "Belize": "Белмopan",
  "Benin": "Порто-Ново",
  "Bhutan": "Тхимпху",
  "Bolivia": "Сукре",
  "Bosnia and Herzegovina": "Сараево",
  "Botswana": "Габороне",
  "Brazil": "Бразилия",
  "Brunei": "Бандар-Сери-Бегаван",
  "Bulgaria": "София",
  "Burkina Faso": "Уагадугу",
  "Burundi": "Бужумбура",
  "Cabo Verde": "Прая",
  "Cambodia": "Пномпен",
  "Cameroon": "Яунде",
  "Canada": "Оттава",
  "Central African Republic": "Банги",
  "Chad": "Нджамена",
  "Chile": "Сантьяго",
  "China": "Бейжинг",
  "Colombia": "Богота",
  "Comoros": "Моронӣ",
  "Congo (Republic)": "Браззавил",
  "Costa Rica": "Сан-Хосе",
  "Croatia": "Загреб",
  "Cuba": "Ҳавана",
  "Cyprus": "Никосия",
  "Czechia": "Прага",
  "Denmark": "Копенгаген",
  "Djibouti": "Ҷибути",
  "Dominica": "Розо",
  "Dominican Republic": "Санто-Доминго",
  "Ecuador": "Кито",
  "Egypt": "Қоҳира",
  "El Salvador": "Сан-Салвадор",
  "Equatorial Guinea": "Малабо",
  "Eritrea": "Асмара",
  "Estonia": "Таллин",
  "Eswatini": "Мбабане",
  "Ethiopia": "Аддис-Абеба",
  "Fiji": "Сува",
  "Finland": "Хелсинки",
  "France": "Париж",
  "Gabon": "Либревил",
  "Gambia": "Банжул",
  "Georgia": "Тбилиси",
  "Germany": "Берлин",
  "Ghana": "Аккра",
  "Greece": "Афина",
  "Grenada": "Сент-Джорҷес",
  "Guatemala": "Гватемала",
  "Guinea": "Конакри",
  "Guinea-Bissau": "Бисау",
  "Guyana": "Джорҷтаун",
  "Haiti": "Порт-о-Пренс",
  "Honduras": "Тегусигалпа",
  "Hungary": "Будапешт",
  "Iceland": "Рейкјавик",
  "India": "Ню-Дели",
  "Indonesia": "Жакарта",
  "Iran": "Теҳрон",
  "Iraq": "Бағдод",
  "Ireland": "Дублин",
  "Israel": "Қудс",
  "Italy": "Рим",
  "Jamaica": "Кингстон",
  "Japan": "Токио",
  "Jordan": "Амман",
  "Kazakhstan": "Нурсултон",
  "Kenya": "Найроби",
  "Kiribati": "Тарава",
  "Kuwait": "Кувайт",
  "Kyrgyzstan": "Бишкек",
  "Laos": "Виентьян",
  "Latvia": "Рига",
  "Lebanon": "Байрут",
  "Lesotho": "Масеру",
  "Liberia": "Монровия",
  "Libya": "Триполи",
  "Liechtenstein": "Вадуц",
  "Lithuania": "Вилнюс",
  "Luxembourg": "Люксембург",
  "Madagascar": "Антананариву",
  "Malawi": "Лилонгве",
  "Malaysia": "Куала-Лумпур",
  "Maldives": "Мале",
  "Mali": "Бамако",
  "Malta": "Валетта",
  "Marshall Islands": "Маджуро",
  "Mauritania": "Нуакшот",
  "Mauritius": "Порт-Луи",
  "Mexico": "Мехико",
  "Micronesia": "Паликир",
  "Moldova": "Кишинёв",
  "Monaco": "Монако",
  "Mongolia": "Улан-Батор",
  "Montenegro": "Подгорица",
  "Morocco": "Рабат",
  "Mozambique": "Мапуто",
  "Myanmar": "Найпидо",
  "Namibia": "Виндхук",
  "Nauru": "Ярен",
  "Nepal": "Катманду",
  "Netherlands": "Амстердам",
  "New Zealand": "Веллингтон",
  "Nicaragua": "Манагуа",
  "Niger": "Ниамей",
  "Nigeria": "Абуджа",
  "North Korea": "Пхеньян",
  "North Macedonia": "Скопие",
  "Norway": "Осло",
  "Oman": "Маскат",
  "Pakistan": "Исламабод",
  "Palau": "Нгерулмуд",
  "Palestine": "Қудс",
  "Panama": "Панама",
  "Papua New Guinea": "Порт-Морсби",
  "Paraguay": "Асунсион",
  "Peru": "Лима",
  "Philippines": "Манила",
  "Poland": "Варшава",
  "Portugal": "Лисбон",
  "Qatar": "Доха",
  "Romania": "Бухарест",
  "Russia": "Маскав",
  "Rwanda": "Кигали",
  "Saint Kitts and Nevis": "Бастер",
  "Saint Lucia": "Кастри",
  "Saint Vincent and the Grenadines": "Кингстаун",
  "Samoa": "Апиа",
  "San Marino": "Сан-Марино",
  "Sao Tome and Principe": "Сан-Томе",
  "Saudi Arabia": "Риёз",
  "Senegal": "Дакар",
  "Serbia": "Белград",
  "Seychelles": "Виктория",
  "Sierra Leone": "Фритаун",
  "Singapore": "Сингапур",
  "Sint Maarten": "Синт-Мартен",
  "Slovakia": "Братислава",
  "Slovenia": "Любляна",
  "Solomon Islands": "Хониара",
  "Somalia": "Могадишу",
  "South Africa": "Претория",
  "South Korea": "Сеул",
  "South Sudan": "Жуба",
  "Spain": "Мадрид",
  "Sri Lanka": "Шри-Ҷаяварденепура-Котте",
  "Sudan": "Хартум",
  "Suriname": "Парамарибо",
  "Sweden": "Стокҳолм",
  "Switzerland": "Берн",
  "Syria": "Шам",
  "Taiwan": "Тайпей",
  "Tajikistan": "Душанбе",
  "Tanzania": "Додома",
  "Thailand": "Бангкок",
  "Timor-Leste": "Дили",
  "Togo": "Ломе",
  "Tonga": "Нукуалофа",
  "Trinidad and Tobago": "Порт-оф-Спейн",
  "Tunisia": "Тунис",
  "Turkey": "Анқара",
  "Turkmenistan": "Ашхобод",
  "Tuvalu": "Фунафути",
  "Uganda": "Кампала",
  "Ukraine": "Киев",
  "United Arab Emirates": "Абу-Дабӣ",
  "United Kingdom": "Лондон",
  "United States": "Вашингтон",
  "Uruguay": "Монтевидео",
  "Uzbekistan": "Тошканд",
  "Vanuatu": "Порт-Вила",
  "Vatican City": "Ватикан",
  "Venezuela": "Каракас",
  "Vietnam": "Ҳаной",
  "Yemen": "Сана",
  "Zambia": "Лусака",
  "Zimbabwe": "Хараре",
  "Anguilla": "Роджтаун",
  "Norfolk Island": "Кингстон",
  "Caribbean Netherlands": "Кёркеден",
  "Turks and Caicos Islands": "Кобернтау",
  "Curaçao": "Виллемстад",
  "British Virgin Islands": "Роуд-Таун",
  "Guernsey": "Сент-Питер-Порт",
  "Mayotte": "Мамудзу",
  "Saint Barthélemy": "Густавия",
  "American Samoa": "Пага-Пага",
  "Ivory Coast": "Ямусукро",
  "Guam": "Хагатна",
  "Falkland Islands": "Стэнли",
  "New Caledonia": "Нумеа",
  "Martinique": "Форт-де-Франс",
  "Republic of the Congo": "Браззавил",
  "Western Sahara": "Эль-Аюн",
  "Åland Islands": "Мариэхамн",
  "Jersey": "Сент-Хелиер",
  "British Indian Ocean Territory": "Диего-Гарсия",
  "Puerto Rico": "Сан-Хуан",
  "French Southern and Antarctic Lands": "Антарктика",
  "Isle of Man": "Дуглас",
  "Gibraltar": "Гибралтар",
  "DR Congo": "Киншаса",
  "Christmas Island": "Флай-Крик",
  "Guadeloupe": "Бас-Тер",
  "United States Virgin Islands": "Шарлотта-Амалиа",
  "Heard Island and McDonald Islands": "Женева",
  "Northern Mariana Islands": "Саипан",
  "Faroe Islands": "Торсхавн",
  "Greenland": "Нуук",
  "Montserrat": "Плимут",
  "United States Minor Outlying Islands": "Виллис-Шенен",
  "Bermuda": "Гамильтон",
  "Svalbard and Jan Mayen": "Лонгйир",
  "Saint Pierre and Miquelon": "Сен-Пьер",
  "Tokelau": "Факафо",
  "Saint Helena, Ascension and Tristan da Cunha": "Сент-Хелена",
  "Cocos (Keeling) Islands": "Бантам",
  "Niue": "Алофи",
  "Kosovo": "Приштина",
  "Wallis and Futuna": "Мата-Уту",
  "French Polynesia": "Папеэте",
  "South Georgia": "Гринвич",
  "Cayman Islands": "Джорджтаун",
  "Pitcairn Islands": "Адамстаун",
  "Antarctica": "Антарктида",
  "French Guiana": "Кайенна",
  "Réunion": "Сен-Дени",
  "Cook Islands": "Аваруа",
  "Saint Martin": "Маригот"
}