export const countryNamesTG: Record<string, string>={
  "Afghanistan": "Афғонистон",
  "Albania": "Албания",
  "Algeria": "Алҷазоир",
  "Andorra": "Андорра",
  "Angola": "Ангола",
  "Antigua and Barbuda": "Антигуа ва Барбуда",
  "Argentina": "Аргентина",
  "Armenia": "Арманистон",
  "Australia": "Аустралия",
  "Austria": "Австрия",
  "Azerbaijan": "Озарбойҷон",
  "Bahamas": "Баҳамҳо",
  "Bahrain": "Баҳрайн",
  "Bangladesh": "Бангладеш",
  "Barbados": "Барбадос",
  "Belarus": "Беларус",
  "Belgium": "Белгия",
  "Belize": "Белиз",
  "Benin": "Бенин",
  "Bhutan": "Бутан",
  "Bolivia": "Боливия",
  "Bosnia and Herzegovina": "Босния ва Ҳерцеговина",
  "Botswana": "Ботсвана",
  "Brazil": "Бразилия",
  "Brunei": "Бруней",
  "Bulgaria": "Булғористон",
  "Burkina Faso": "Буркина-Фасо",
  "Burundi": "Бурундӣ",
  "Cabo Verde": "Кабо Верде",
  "Cambodia": "Камбоджа",
  "Cameroon": "Камерун",
  "Canada": "Канада",
  "Central African Republic": "Ҷумҳурии Африқои Марказӣ",
  "Chad": "Ҷад",
  "Chile": "Чили",
  "China": "Чин",
  "Colombia": "Колумбия",
  "Comoros": "Коморос",
  "Congo (Republic)": "Конго (Ҷумҳурии)",
  "Costa Rica": "Коста-Рика",
  "Croatia": "Хорватия",
  "Cuba": "Куба",
  "Cyprus": "Кипр",
  "Czechia": "Чехия",
  "Denmark": "Дания",
  "Djibouti": "Ҷибутӣ",
  "Dominica": "Доминика",
  "Dominican Republic": "Ҷумҳурии Доминикан",
  "Ecuador": "Эквадор",
  "Egypt": "Миср",
  "El Salvador": "Эл Салвадор",
  "Equatorial Guinea": "Гвинеяи Экваторӣ",
  "Eritrea": "Эритрея",
  "Estonia": "Эстония",
  "Eswatini": "Эсватини",
  "Ethiopia": "Эфиопия",
  "Fiji": "Фижӣ",
  "Finland": "Финландия",
  "France": "Фаронса",
  "Gabon": "Габон",
  "Gambia": "Гамбия",
  "Georgia": "Гурҷистон",
  "Germany": "Олмон",
  "Ghana": "Гана",
  "Greece": "Юнон",
  "Grenada": "Гренада",
  "Guatemala": "Гватемала",
  "Guinea": "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  "Guyana": "Гайана",
  "Haiti": "Ҳаити",
  "Honduras": "Ҳондурас",
  "Hungary": "Маҷористон",
  "Iceland": "Исландия",
  "India": "Ҳиндистон",
  "Indonesia": "Индонезия",
  "Iran": "Эрон",
  "Iraq": "Ироқ",
  "Ireland": "Ирландия",
  "Israel": "Исроил",
  "Italy": "Италия",
  "Jamaica": "Ямайка",
  "Japan": "Ҷопон",
  "Jordan": "Урдун",
  "Kazakhstan": "Қазоқистон",
  "Kenya": "Кения",
  "Kiribati": "Кирибати",
  "Kuwait": "Кувайт",
  "Kyrgyzstan": "Қирғизистон",
  "Laos": "Лаос",
  "Latvia": "Латвия",
  "Lebanon": "Лубнон",
  "Lesotho": "Лесото",
  "Liberia": "Либерия",
  "Libya": "Либия",
  "Liechtenstein": "Лихтенштейн",
  "Lithuania": "Литва",
  "Luxembourg": "Люксембург",
  "Madagascar": "Мадагаскар",
  "Malawi": "Малави",
  "Malaysia": "Малайзия",
  "Maldives": "Малдив",
  "Mali": "Мали",
  "Malta": "Малта",
  "Marshall Islands": "Ҷазираҳои Маршал",
  "Mauritania": "Мауритания",
  "Mauritius": "Мауритус",
  "Mexico": "Мексика",
  "Micronesia": "Микронезия",
  "Moldova": "Молдова",
  "Monaco": "Монако",
  "Mongolia": "Муғулистон",
  "Montenegro": "Черногория",
  "Morocco": "Марокко",
  "Mozambique": "Мозамбик",
  "Myanmar": "Мянмар",
  "Namibia": "Намибия",
  "Nepal": "Непал",
  "Netherlands": "Нидерланд",
  "New Zealand": "Зеландияи Нав",
  "Nicaragua": "Никарагуа",
  "Niger": "Нигер",
  "Nigeria": "Нигерия",
  "North Korea": "Куриёи Шимолӣ",
  "North Macedonia": "Македониёи Шимолӣ",
  "Norway": "Норвегия",
  "Oman": "Умон",
  "Pakistan": "Покистон",
  "Palau": "Палау",
  "Palestine": "Фаластин",
  "Panama": "Панама",
  "Papua New Guinea": "Папуа — Гвинеяи Нав",
  "Paraguay": "Парагвай",
  "Peru": "Перу",
  "Philippines": "Филиппин",
  "Poland": "Лаҳистон",
  "Portugal": "Португалия",
  "Qatar": "Қатар",
  "Romania": "Руминӣ",
  "Russia": "Русия",
  "Rwanda": "Руанда",
  "Saint Kitts and Nevis": "Сент-Китс ва Невис",
  "Saint Lucia": "Сент-Люсия",
  "Saint Vincent and the Grenadines": "Сент-Винсент ва Гренадинҳо",
  "Samoa": "Самоа",
  "San Marino": "Сан-Марино",
  "Sao Tome and Principe": "Сан-Томе ва Принсипӣ",
  "Saudi Arabia": "Арабистони Саудӣ",
  "Senegal": "Сенегал",
  "Serbia": "Сербия",
  "Seychelles": "Сейшелҳо",
  "Sierra Leone": "Сьерра-Леоне",
  "Singapore": "Сингапур",
  "Sint Maarten": "Синт-Мартен",
  "Slovakia": "Словакия",
  "Slovenia": "Словения",
  "Solomon Islands": "Ҷазираҳои Соломон",
  "Somalia": "Сомалӣ",
  "South Africa": "Ҷануби Африқо",
  "South Korea": "Куриёи Ҷанубӣ",
  "South Sudan": "Ҷануби Судон",
  "Spain": "Испания",
  "Sri Lanka": "Шри-Ланка",
  "Sudan": "Судан",
  "Suriname": "Суринам",
  "Sweden": "Шветсия",
  "Switzerland": "Швейтсария",
  "Syria": "Сурия",
  "Taiwan": "Тайван",
  "Tajikistan": "Тоҷикистон",
  "Tanzania": "Танзания",
  "Thailand": "Таиланд",
  "Timor-Leste": "Тимор-Лешти",
  "Togo": "Того",
  "Tonga": "Тонга",
  "Trinidad and Tobago": "Тринити ва Тобаго",
  "Tunisia": "Тунис",
  "Turkey": "Туркия",
  "Turkmenistan": "Туркманистон",
  "Tuvalu": "Тувалу",
  "Uganda": "Уганда",
  "Ukraine": "Украина",
  "United Arab Emirates": "Имороти Муттаҳидаи Араб",
  "United Kingdom": "Иттиҳоди Британия",
  "United States": "Иёлоти Муттаҳида",
  "Uruguay": "Уругвай",
  "Uzbekistan": "Узбекистон",
  "Vanuatu": "Вануату",
  "Vatican City": "Ватикан",
  "Venezuela": "Венесуэла",
  "Vietnam": "Ветнам",
  "Yemen": "Яман",
  "Zambia": "Замбия",
  "Zimbabwe": "Зимбабве",
  "Anguilla": "Ангуилла",
  "Norfolk Island": "Ҷазираи Норфолк",
  "Caribbean Netherlands": "Нидерландҳои Карибӣ",
  "Turks and Caicos Islands": "Ҷазираҳои Туркс ва Кайкос",
  "Curaçao": "Кюрасао",
  "British Virgin Islands": "Ҷазираҳои Вирҷинияи Британия",
   "Guernsey": "Гернси",
  "Mayotte": "Майотт",
  "Saint Barthélemy": "Сент-Бартелеми",
  "American Samoa": "Самоаи Амрикоӣ",
  "Ivory Coast": "Кот-д’Ивуар",
  "Guam": "Гуам",
  "Nauru": "Науру",
  "Falkland Islands": "Ҷазираҳои Фолкланд",
  "New Caledonia": "Каледонияи Нав",
  "Martinique": "Мартинӣк",
  "Republic of the Congo": "Ҷумҳурии Конго",
  "São Tomé and Príncipe": "Сан-Томе ва Принсипӣ",
  "Western Sahara": "Саҳрои Ғарбӣ",
  "Åland Islands": "Ҷазираҳои Оланд",
  "Jersey": "Ҷерсӣ",
  "British Indian Ocean Territory": "Ҳудуди Британия дар Уқёнуси Ҳинду",
  "Puerto Rico": "Пуэрто-Рико",
  "French Southern and Antarctic Lands": "Заминҳои Ҷанубӣ ва Антарктидаи Фаронса",
  "Cape Verde": "Кабо Верде",
  "Isle of Man": "Ҷазираи Ман",
  "Gibraltar": "Ҷибралтар",
  "DR Congo": "Ҷумҳурии Демократии Конго",
  "Christmas Island": "Ҷазираи Кристмас",
  "Guadeloupe": "Гваделупе",
  "United States Virgin Islands": "Ҷазираҳои Вирҷинияи ИМА",
  "Heard Island and McDonald Islands": "Ҷазираҳои Ҳерд ва Макдоналд",
  "Northern Mariana Islands": "Ҷазираҳои Шимолии Мариана",
  "Faroe Islands": "Ҷазираҳои Фарер",
  "Greenland": "Гренландия",
   "Montserrat": "Монсеррат",
  "United States Minor Outlying Islands": "Ҷазираҳои хурди ИМА",
  "Bermuda": "Бермуд",
  "Svalbard and Jan Mayen": "Свалбард ва Ян-Майен",
  "Saint Pierre and Miquelon": "Сент-Пьер ва Микелон",
  "Tokelau": "Токелау",
  "Saint Helena, Ascension and Tristan da Cunha": "Сент-Хелена, Ассенсион ва Тристан да Кунья",
  "Cocos (Keeling) Islands": "Ҷазираҳои Кокос (Килинг)",
  "Niue": "Ниуэ",
  "Kosovo": "Косово",
  "Wallis and Futuna": "Уоллис ва Футуна",
  "French Polynesia": "Полинезияи Фаронса",
  "South Georgia": "Ҷануби Ҷорҷия",
  "Cayman Islands": "Ҷазираҳои Кайман",
  "Pitcairn Islands": "Ҷазираҳои Питкэрн",
  "Antarctica": "Антарктида",
  "French Guiana": "Гвинаи Фаронса",
  "Réunion": "Реюнион",
  "Cook Islands": "Ҷазираҳои Кук",
  "Saint Martin": "Сент-Мартин"
};
